pipeline{
	agent any
	
	tools {
		maven "mvn"
	}
	stages {
		stage ('Build'){
			steps{
			
			// get code from github
			git url: 'https://github.com/ritxsh7/devops-demo.git'
			
			script{
				if(isUnix()){
					sh "mvn clean package"
				}
				else{
					bat "mvn clean package"
				}
			}
			}
		}
		stage('Integration Test'){
			steps{
			script{
				if(isUnix()){
					sh "mvn clean verify"
				}
				else{
					bat "mvn clean verify"
				}
			}
			}
		}
		stage('Build Docker Image and Push Image To Hub'){
			steps{
			script{
				if(isUnix()){
					sh "sudo docker buildx build . --tag patilritesh/myapp:latest --push"
				}
				else{
					bat "sudo docker buildx build . --tag patilritesh/myapp:latest --push"
				}
			}
			}
		}
		stage('Deploy To Cloud'){
			steps{
			script{
				if(isUnix()){
					sh "kubectl apply -f deployment"
				}
				else{
					bat "kubectl apply -f deployment"
				}
			}
			}
		}
		
		
	}
}
