apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-configmap-reader
  namespace: default
subjects:
  - kind: ServiceAccount
    name: configmap-reader
    namespace: default
    apiGroup: ""
roleRef:
  kind: Role
  name: role-configmap-reader
  apiGroup: rbac.authorization.k8s.io