apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-service
  labels:
    app: myapp-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-service
  template:
    metadata:
      labels:
        app: myapp-service
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: myapp-config-volume
      containers:
      - name: myapp-service
        image: kpradeep/my-app:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
           limits:
             cpu: "500m"
             memory: "512Mi"
           requests:
             cpu: "250m"
             memory: "256Mi"
        volumeMounts:
           - name: config-volume
             mountPath: "/config"
